import
ibm_dbdictio
nary={}
defprintTableData(conn):
sql="SELECT*FROMuserdetails"out=i
bm_db.exec_immediate(conn,sql)do
cument=ibm_db.fetch_assoc(out)wh
iledocument!=False:
dictionary.update({document['USERNAME']:
documen
t['PASSWORD']})document=
ibm_db.fetch_assoc(out)def
insertTableData(conn,rollno,username,email,password):sql="I
NSERTINTO
userdetails(rollno,username,email,password)VALUES
({},'{}','{}','{}')".format(rollno,username,email,password)out=
ibm_db.exec_immediate(conn,sql)
print('Numberofaffectedrows:
',ibm_db.num_rows(out),"\n")defupdateTableData(conn,r
ollno,username,email,password):
sql="UPDATEuserdetailsSET(username,email,password)=('{}','{}','{}')
WHERErollno={}".format(username,email,password,rollno)
out=ibm_db.exec_immediate(conn,sql)
print('Numberofaffectedrows:',ibm_db.num_rows(out),
"\n")defdeleteTableData(conn,rollno):
sql="DELETEFROMuserdetailsWHERErollno={}".format(rollno